DROP TABLE IF EXISTS trade_signals;
create table trade_signals (
     id int generated by default as identity (start with 1) primary key,
     signal bigint not null,
     type varchar not null,
     calculate tinyint not null default false
);

DROP TABLE IF EXISTS signal_specifications;
create table signal_specifications (
     id int generated by default as identity (start with 1) primary key,
     signal_id bigint not null,
     param_nr bigint not null,
     param_value bigint not null
);